config/routes.rb
BusPlus::Application.routes.draw do
  
  resources :drivers, only: :index
  resources :vehicles, only: :index
  resources :passengers, only: :index
  resources :candidates, only: :index
  
  match "/api/match" => "api#match", via: :get, as: 'match'
  match "/api" => 'api#index', via: :get, as: 'api'

  scope '/api' do
    resources :drivers
    resources :vehicles do
      collection do
        get :near
      end
    end
    resources :passengers
    resources :candidates
    match '/:anything' => 'api/base#error', conditions: { anything: /.*/ }
  end

  match "/passenger" => 'home#passenger', via: :get, as: 'passenger'
  match "/driver" => 'home#driver', via: :get, as: 'driver'
  root to: "home#index"

end

app/models/candidate.rb
class Candidate < ActiveRecord::Base

  belongs_to :passenger
  belongs_to :vehicle
  
  validates_presence_of :passenger_id, :vehicle_id
  validates :bid, numericality: true, allow_nil: true
  
  attr_accessible :passenger_id, :vehicle_id, :bid, :assigned_at

  after_create :send_bid_request
  after_update :send_assignment, unless: Proc.new {|e| e.assigned_at.blank?}
  
  scope :pending_bid, where(bid: nil)
  scope :unassigned, where('bid is not null').where(assigned_at: nil)
  scope :assigned, where('assigned_at is not null')
  
  def send_bid_request
    CandidateBidRequest.delay.send_bid_request(id)
  end

  def send_assignment
    CandidateAssignment.delay.send_assignment(passenger_id, vehicle_id)
  end

  def assign!
    passenger.assign! vehicle_id
    vehicle.decrement_seat_count!
    self.update_attributes(assigned_at: Time.now)
  end
  
end

app/models/driver.rb
class Driver < ActiveRecord::Base

  has_one :vehicle, dependent: :destroy

  attr_accessible :email, :license_number
  
  validates_presence_of :email, :license_number
  validates_uniqueness_of :email
  validates_uniqueness_of :license_number, scope: :email

end

app/models/passenger.rb
class Passenger < ActiveRecord::Base

  has_many :candidates, dependent: :destroy
  belongs_to :vehicle
  
  validates_presence_of :start_latitude, :start_longitude, :end_latitude, :end_longitude, :token
  validates_numericality_of :start_latitude, :start_longitude, :end_latitude, :end_longitude

  attr_accessible :start_latitude, :start_longitude, :end_latitude, :end_longitude, :position, :token
  
  after_create :find_candidates
  before_destroy :release_from_vehicle
  
  def find_candidates
    CandidateSearch.delay.search(id)
  end

  def assign!(assigned_vehicle_id)
    puts "assigned passenger #{id} to vehicle #{assigned_vehicle_id}"
    self.assigned_at = Time.now
    self.vehicle_id = assigned_vehicle_id
    self.save
  end

  def release_from_vehicle
    vehicle.increment_seat_count! unless vehicle.nil?
  end
  
end

app/models/path_element.rb
class PathElement < ActiveRecord::Base
  
  has_and_belongs_to_many :manifests
  belongs_to :passenger
  
  validates_presence_of :passenger_id, :start_latitude, :start_longitude, :start_time, :end_latitude, :end_longitude, :end_time
  
end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :driver
  has_many :passengers, order: 'position asc'
  has_many :candidates, dependent: :destroy
  
  validates_presence_of :driver_id, :latitude, :longitude, :token
  validates_numericality_of :latitude, :longitude

  attr_accessible :latitude, :longitude, :driver_id, :seats_available, :on_duty, :token
  
  scope :on_duty, where(on_duty: true)
  scope :with_vacancy, where('seats_available > 0')
  
  def waypoints
    passengers.map {|s| [[s.start_latitude,s.start_longitude],[s.end_latitude,s.end_longitude]]}.flatten
  end

  def decrement_seat_count!
    self.update_attributes(seats_available: seats_available-1)
  end
  
  def increment_seat_count!
    self.update_attributes(seats_available: seats_available+1)
  end
  
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController

  respond_to :json, :xml
  
  def error
    respond_to do |format|
      format.json { render json: {errors: "Invalid request"}, status: :not_found }
      format.xml { render xml: {errors: "Invalid request"}, status: :not_found }
    end
  end
  
end

app/controllers/api_controller.rb
class ApiController < ApplicationController

  def index
  end
  
  def match
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  respond_to :json, :xml
  
  def index
    respond_to do |format|
      format.html
      format.json { head :forbidden }
      format.xml { head :forbidden }
    end
  end
  
  def create
    head :forbidden
  end
  
  def show
    respond_with(@candidate = Candidate.find(params[:id]))
  end
  
  def update
    @candidate = Candidate.find(params[:id])
    
    if @candidate.update_attributes(params[:candidate])
      respond_with(@candidate, status: :ok)
    else
      respond_with(@candidate, status: :unprocessable_entity)
    end
  end
  
  def destroy
    head :forbidden
  end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController

  respond_to :json, :xml
  
  def index
    respond_to do |format|
      format.html { render layout: 'api' }
      format.json { head :forbidden }
      format.xml { head :forbidden }
    end
  end

  def show
    respond_with(@driver = Driver.find(params[:id]))
  end
  
  def create
    @driver = Driver.new(params[:driver])
    @driver.save
    respond_with(@driver)
  end
  
  def update
    @driver = Driver.find(params[:id])
    
    @driver.update_attributes(params[:driver])
    respond_with(@driver)
  end
  
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy
    
    head :ok
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
end

app/controllers/passengers/paths_controller.rb
class Passengers::PathsController < ApplicationController

  def show
    @passenger = Passenger.find(params[:passenger_id])
    @path = @passenger.path
  end

end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController

  respond_to :json, :xml
  
  def index
    respond_to do |format|
      format.html { render layout: 'api' }
      format.json { head :forbidden }
      format.xml { head :forbidden }
    end
  end

  def create
    @passenger = Passenger.new(params[:passenger])
    
    @passenger.save
    respond_with(@passenger)
  end

  def show
    respond_with(@passenger = Passenger.find(params[:id]))
  end
  
  def update
    head :forbidden
  end
  
  def destroy
    @passenger = Passenger.find(params[:id])
    @passenger.destroy
    
    head :ok
  end

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  respond_to :json, :xml
  
  def index
    respond_to do |format|
      format.html { render layout: 'api' }
      format.json { head :forbidden }
      format.xml { head :forbidden }
    end
  end

  def near
    @vehicles = Vehicle.on_duty.with_vacancy.near(params[:latitude].to_f,params[:longitude].to_f)
    respond_to do |format|
      format.json { render json: @vehicles.count, status: :ok }
      format.xml {  render xml: @vehicles.count, status: :ok }
    end
  end
  
  def create
    @vehicle = Vehicle.new(params[:vehicle])
    @vehicle.save
    respond_with(@vehicle)
  end
  
  def show
    respond_with(@vehicle = Vehicle.includes(:passengers).find(params[:id]), include: { passengers: { except: :token } })
  end
  
  def update
    @vehicle = Vehicle.find(params[:id])
    
    @vehicle.update_attributes(params[:vehicle])
    respond_with(@vehicle)
  end
  
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy
    
    head :ok
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passengers/paths_helper.rb
module Passengers::PathsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/destinations/index.haml
%h1 destination
%ul.api
	%li 
		%span POST /passengers/1/destination
		%p.request {"destination":{"latitude":26.01, "longitude":-82.01}}
		%p.response {"passenger":{"id":123, "latitude":26.0, "longitude":-82.0, "segment": {"start_latitude": 26.0, "start_longitude": -82.0, "end_latitude": 26.01, "end_longitude": -82.01}}}

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-4535281-8']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/api.haml
!!! 5
%html
	%head
		%title 
			bus+ API
			= "- #{yield(:title)}" unless yield(:title).blank?
		= stylesheet_link_tag :all
		%link{:rel => "stylesheet", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/trontastic/jquery-ui.css", :type => "text/css"}
		= javascript_include_tag :defaults
		= csrf_meta_tag
		= render 'layouts/google_analytics'
	%body
		%header
			%p#logo bus+
			%p#tagline API Spec

			%nav
				%ul
					%li{class: (controller.controller_name=='api' ? 'current' : '')}= link_to 'overview', api_path
					%li{class: (controller.controller_name=='drivers' ? 'current' : '')}= link_to 'drivers', drivers_path
					%li{class: (controller.controller_name=='vehicles' ? 'current' : '')}= link_to 'vehicles', vehicles_path
					%li{class: (controller.controller_name=='passengers' ? 'current' : '')}= link_to 'passengers', passengers_path
		#main= yield
		%footer
			Copyright © 2012 Migrant Studios. All Rights Reserved.

app/views/layouts/application.haml
!!! 5
%html
	%head
		%title 
			BusPlus
			= "- #{yield(:title)}" unless yield(:title).blank?
		= stylesheet_link_tag :all
		%link{:rel => "stylesheet", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/trontastic/jquery-ui.css", :type => "text/css"}
		= javascript_include_tag :defaults
		= csrf_meta_tag
	%body
		%header
			%p#logo BUS PLUS
			%p#tagline 
				Scalable
				%br
				On-Demand
				%br
				Transportation
			%nav
				%ul
					%li{class: (controller.controller_name=='home' ? 'current' : '')}= link_to 'overview', root_path
					%li{class: (controller.controller_name=='drivers' ? 'current' : '')}= link_to 'drivers', drivers_path
					%li{class: (controller.controller_name=='vehicles' ? 'current' : '')}= link_to 'vehicles', vehicles_path
					%li{class: (controller.controller_name=='passengers' ? 'current' : '')}= link_to 'passengers', passengers_path
		#main= yield
		%footer
			Copyright © 2012 Migrant Studios. All Rights Reserved.

app/views/layouts/home.haml
!!! 5
%html
	%head
		%title 
			bus+
			= "- #{yield(:title)}" unless yield(:title).blank?
		= stylesheet_link_tag :all
		%link{:rel => "stylesheet", :href => "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/trontastic/jquery-ui.css", :type => "text/css"}
		= javascript_include_tag :defaults
		= csrf_meta_tag
		= render 'layouts/google_analytics'
	%body
		%header
			%p#logo bus+
			%p#tagline 
				Scalable
				%br
				On-Demand
				%br
				Transportation
			%nav
				%ul
					%li{class: (controller.action_name=='index' ? 'current' : '')}= link_to 'overview', root_path
					%li{class: (controller.action_name=='passenger' ? 'current' : '')}= link_to 'passenger', passenger_path
					%li{class: (controller.action_name=='driver' ? 'current' : '')}= link_to 'driver', driver_path
					%li= link_to 'developers', api_path, target: '_new'
		#main= yield
		%footer
			Copyright © 2012 Migrant Studios. All Rights Reserved.